services:
  - type: worker
    name: selenium-scraper
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: "python scrape_jobs.py"
