services:
  - type: web
    name: selenium-job-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scrape_jobs.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
