services:
  - type: worker
    name: job-bot-worker
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python scrape_jobs.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false

